/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ByebyeIndexImport } from './routes/byebye/index'
import { Route as DashboardLayoutImport } from './routes/dashboard/_layout'
import { Route as AuthLayoutImport } from './routes/auth/_layout'
import { Route as DashboardLayoutIndexImport } from './routes/dashboard/_layout/index'
import { Route as DashboardLayoutChallengeIndexImport } from './routes/dashboard/_layout/challenge/index'
import { Route as AuthLayoutMagiclinkIndexImport } from './routes/auth/_layout/magiclink/index'
import { Route as DashboardLayoutChallengeChallengeIdIndexImport } from './routes/dashboard/_layout/challenge/$challengeId/index'

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')()
const AuthImport = createFileRoute('/auth')()
const AuthLayoutSigninRouteLazyImport = createFileRoute(
  '/auth/_layout/signin',
)()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ByebyeIndexRoute = ByebyeIndexImport.update({
  path: '/byebye/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)

const DashboardLayoutIndexRoute = DashboardLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const AuthLayoutSigninRouteLazyRoute = AuthLayoutSigninRouteLazyImport.update({
  path: '/signin',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./routes/auth/_layout/signin/route.lazy').then((d) => d.Route),
)

const DashboardLayoutChallengeIndexRoute =
  DashboardLayoutChallengeIndexImport.update({
    path: '/challenge/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const AuthLayoutMagiclinkIndexRoute = AuthLayoutMagiclinkIndexImport.update({
  path: '/magiclink/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const DashboardLayoutChallengeChallengeIdIndexRoute =
  DashboardLayoutChallengeChallengeIdIndexImport.update({
    path: '/challenge/$challengeId/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_layout': {
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_layout': {
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof DashboardRoute
    }
    '/byebye/': {
      preLoaderRoute: typeof ByebyeIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/_layout/signin': {
      preLoaderRoute: typeof AuthLayoutSigninRouteLazyImport
      parentRoute: typeof AuthLayoutImport
    }
    '/dashboard/_layout/': {
      preLoaderRoute: typeof DashboardLayoutIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/auth/_layout/magiclink/': {
      preLoaderRoute: typeof AuthLayoutMagiclinkIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/dashboard/_layout/challenge/': {
      preLoaderRoute: typeof DashboardLayoutChallengeIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/challenge/$challengeId/': {
      preLoaderRoute: typeof DashboardLayoutChallengeChallengeIdIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([
    AuthLayoutRoute.addChildren([
      AuthLayoutSigninRouteLazyRoute,
      AuthLayoutMagiclinkIndexRoute,
    ]),
  ]),
  DashboardRoute.addChildren([
    DashboardLayoutRoute.addChildren([
      DashboardLayoutIndexRoute,
      DashboardLayoutChallengeIndexRoute,
      DashboardLayoutChallengeChallengeIdIndexRoute,
    ]),
  ]),
  ByebyeIndexRoute,
])

/* prettier-ignore-end */
