/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ByebyeIndexImport } from './routes/byebye/index'
import { Route as homeIndexImport } from './routes/(home)/index'
import { Route as AuthLayoutImport } from './routes/auth/_layout'
import { Route as ProfileLayoutProfileLayoutImport } from './routes/_profile-layout/_profile-layout'
import { Route as ProfileLayoutSettingsIndexImport } from './routes/_profile-layout/settings/index'
import { Route as AuthLayoutMagiclinkIndexImport } from './routes/auth/_layout/magiclink/index'
import { Route as ProfileLayoutProfileLayoutDashboardIndexImport } from './routes/_profile-layout/_profile-layout.dashboard/index'
import { Route as ProfileLayoutProfileLayoutChallengesIndexImport } from './routes/_profile-layout/_profile-layout.challenges/index'
import { Route as ProfileLayoutProfileLayoutChallengesChallengeIdIndexImport } from './routes/_profile-layout/_profile-layout.challenges/$challengeId/index'
import { Route as ProfileLayoutProfileLayoutChallengesChallengeIdLogsIndexImport } from './routes/_profile-layout/_profile-layout.challenges/$challengeId/logs/index'
import { Route as ProfileLayoutProfileLayoutChallengesChallengeIdLogsNewImport } from './routes/_profile-layout/_profile-layout.challenges/$challengeId/logs/new'
import { Route as ProfileLayoutProfileLayoutChallengesChallengeIdLogsLogIdIndexImport } from './routes/_profile-layout/_profile-layout.challenges/$challengeId/logs/$logId/index'

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')()
const AuthLayoutSigninRouteLazyImport = createFileRoute(
  '/auth/_layout/signin',
)()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const ByebyeIndexRoute = ByebyeIndexImport.update({
  path: '/byebye/',
  getParentRoute: () => rootRoute,
} as any)

const homeIndexRoute = homeIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)

const ProfileLayoutProfileLayoutRoute = ProfileLayoutProfileLayoutImport.update(
  {
    id: '/_profile-layout/_profile-layout',
    getParentRoute: () => rootRoute,
  } as any,
)

const ProfileLayoutSettingsIndexRoute = ProfileLayoutSettingsIndexImport.update(
  {
    path: '/settings/',
    getParentRoute: () => rootRoute,
  } as any,
)

const AuthLayoutSigninRouteLazyRoute = AuthLayoutSigninRouteLazyImport.update({
  path: '/signin',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./routes/auth/_layout/signin/route.lazy').then((d) => d.Route),
)

const AuthLayoutMagiclinkIndexRoute = AuthLayoutMagiclinkIndexImport.update({
  path: '/magiclink/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const ProfileLayoutProfileLayoutDashboardIndexRoute =
  ProfileLayoutProfileLayoutDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => ProfileLayoutProfileLayoutRoute,
  } as any)

const ProfileLayoutProfileLayoutChallengesIndexRoute =
  ProfileLayoutProfileLayoutChallengesIndexImport.update({
    path: '/challenges/',
    getParentRoute: () => ProfileLayoutProfileLayoutRoute,
  } as any)

const ProfileLayoutProfileLayoutChallengesChallengeIdIndexRoute =
  ProfileLayoutProfileLayoutChallengesChallengeIdIndexImport.update({
    path: '/challenges/$challengeId/',
    getParentRoute: () => ProfileLayoutProfileLayoutRoute,
  } as any)

const ProfileLayoutProfileLayoutChallengesChallengeIdLogsIndexRoute =
  ProfileLayoutProfileLayoutChallengesChallengeIdLogsIndexImport.update({
    path: '/challenges/$challengeId/logs/',
    getParentRoute: () => ProfileLayoutProfileLayoutRoute,
  } as any)

const ProfileLayoutProfileLayoutChallengesChallengeIdLogsNewRoute =
  ProfileLayoutProfileLayoutChallengesChallengeIdLogsNewImport.update({
    path: '/challenges/$challengeId/logs/new',
    getParentRoute: () => ProfileLayoutProfileLayoutRoute,
  } as any)

const ProfileLayoutProfileLayoutChallengesChallengeIdLogsLogIdIndexRoute =
  ProfileLayoutProfileLayoutChallengesChallengeIdLogsLogIdIndexImport.update({
    path: '/challenges/$challengeId/logs/$logId/',
    getParentRoute: () => ProfileLayoutProfileLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_profile-layout/_profile-layout': {
      preLoaderRoute: typeof ProfileLayoutProfileLayoutImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_layout': {
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof AuthRoute
    }
    '/(home)/': {
      preLoaderRoute: typeof homeIndexImport
      parentRoute: typeof rootRoute
    }
    '/byebye/': {
      preLoaderRoute: typeof ByebyeIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/_layout/signin': {
      preLoaderRoute: typeof AuthLayoutSigninRouteLazyImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_profile-layout/settings/': {
      preLoaderRoute: typeof ProfileLayoutSettingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/_profile-layout/_profile-layout/challenges/': {
      preLoaderRoute: typeof ProfileLayoutProfileLayoutChallengesIndexImport
      parentRoute: typeof ProfileLayoutProfileLayoutImport
    }
    '/_profile-layout/_profile-layout/dashboard/': {
      preLoaderRoute: typeof ProfileLayoutProfileLayoutDashboardIndexImport
      parentRoute: typeof ProfileLayoutProfileLayoutImport
    }
    '/auth/_layout/magiclink/': {
      preLoaderRoute: typeof AuthLayoutMagiclinkIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_profile-layout/_profile-layout/challenges/$challengeId/': {
      preLoaderRoute: typeof ProfileLayoutProfileLayoutChallengesChallengeIdIndexImport
      parentRoute: typeof ProfileLayoutProfileLayoutImport
    }
    '/_profile-layout/_profile-layout/challenges/$challengeId/logs/new': {
      preLoaderRoute: typeof ProfileLayoutProfileLayoutChallengesChallengeIdLogsNewImport
      parentRoute: typeof ProfileLayoutProfileLayoutImport
    }
    '/_profile-layout/_profile-layout/challenges/$challengeId/logs/': {
      preLoaderRoute: typeof ProfileLayoutProfileLayoutChallengesChallengeIdLogsIndexImport
      parentRoute: typeof ProfileLayoutProfileLayoutImport
    }
    '/_profile-layout/_profile-layout/challenges/$challengeId/logs/$logId/': {
      preLoaderRoute: typeof ProfileLayoutProfileLayoutChallengesChallengeIdLogsLogIdIndexImport
      parentRoute: typeof ProfileLayoutProfileLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  ProfileLayoutProfileLayoutRoute.addChildren([
    ProfileLayoutProfileLayoutChallengesIndexRoute,
    ProfileLayoutProfileLayoutDashboardIndexRoute,
    ProfileLayoutProfileLayoutChallengesChallengeIdIndexRoute,
    ProfileLayoutProfileLayoutChallengesChallengeIdLogsNewRoute,
    ProfileLayoutProfileLayoutChallengesChallengeIdLogsIndexRoute,
    ProfileLayoutProfileLayoutChallengesChallengeIdLogsLogIdIndexRoute,
  ]),
  AuthRoute.addChildren([
    AuthLayoutRoute.addChildren([
      AuthLayoutSigninRouteLazyRoute,
      AuthLayoutMagiclinkIndexRoute,
    ]),
  ]),
  homeIndexRoute,
  ByebyeIndexRoute,
  ProfileLayoutSettingsIndexRoute,
])

/* prettier-ignore-end */
